# LER O ARQUIVO DE CONFIGURAÇÃO (JSON)
# SE O ARQUIVO NÃO EXISTIR --> LANÇAR ERRO --> FINAL STATE
# SE O ARQUIVO ESTIVER FORA DE PADRÃO --> LANÇAR ERRO --> FINAL STATE
# SE TUDO ESTIVER CERTO IR PARA A FUNC CREATE_QUEUE_ITEMS# 